### ISSUE TITLE
did some of the acmeair benchmarks break recently?

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/benchmarking#57]
https://benchmarking.nodejs.org/

some are showing no ops/s on master with very low memory usage

@nodejs/benchmarking

**Comment by gareth-ellis** [comment]
Indeed,

This appears to be linked to  https://github.com/nodejs/node/issues/8051

I'm unable to reproduce locally so I am guessing that it is a particular version of module that isn't interacting happily with the change that 8051 refers to.

@mhdawson is currently out, as far as I'm aware he's the only one with access to the benchmark machine.

I would like a list of module versions we currently have, so we can work out which module is breaking and why.

I also requested output from npm ls in 8051, however I've not seen any response yet.

**Comment by gareth-ellis** [comment]
Upgrading mongodb to 2.0.x seems to fix the problem.

I'd like to understand which bit of mongo is using timers (as that's the code change that seems to have broken mongo). 

in the mean time we could back up our current config on the benchmark server and give a build a go with the package.json changed to use mongo 2.0.x.

**Comment by mhdawson** [comment]
Ran out of time today, should get to fixing the community benchmark server tomorrow

**Comment by mhdawson** [comment]
Ok believe we have fixed up the benchmarks.  Will leave this open for a few days, provided we get good data in the graphs I'll then close.

**Comment by ofrobots** [comment]
To be clear, you fixed this by changing the mongo version used by the benchmark? Could this change be submitted upstream into acmeair-nodejs?

**Comment by gareth-ellis** [comment]
Yes - I increased the mongodb requirement in package.json from 1.4.x to 2.0.x. I can raise a pull request in the acmeair repo. I still have a to do to identify which part of mongodb doesn't like the recent timer change.

**Comment by gareth-ellis** [comment]
This is resolved now and a pr accepted in the acmeair repo, so will close
